<?
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["6"]="D";
$PERM["bitrix"]["7"]="D";
$PERM["obyavleniya-"]["8"]="W";
$PERM["o-servise"]["8"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["6"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["7"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>